name: Test Selenium con GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install ChromeDriver (version compatible con Chrome 131)
        run: |
          curl -sSL https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chromedriver-linux64.zip -o chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Verify ChromeDriver installation
        run: chromedriver --version

      - name: Install http-server
        run: npm install -g http-server

      - name: Start HTTP server
        run: |
          http-server . -p 8081 &
          sleep 5

      - name: Run tests with Selenium
        run: npm test
