name: Test Selenium con GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install ChromeDriver version compatible with Chrome 131
        run: |
          VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131)  # Obtén la última versión compatible con Chrome 131
          curl -O https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run tests with Selenium
        run: npm test
